// Copyright 2026 IOTA Stiftung.
// SPDX-License-Identifier: Apache-2.0.
// This file is generated by ts-to-schema, do not edit it directly.
// @ts-nocheck
/* cspell:disable */
import type { ICompiledValidator } from "@3sixty/data-core";
import * as external0 from "../models/auditableItemGraphAuditMode.js";
import * as external1 from "@3sixty/data-json-ld";
import * as external2 from "@3sixty/immutable-proof-models";
const MESSAGES = [
	"must be string",
	"must be object",
	"must be equal to constant",
	"must NOT have fewer than 1 items",
	"must be array",
	"must match a schema in anyOf",
	"must be boolean",
	"must NOT have fewer than 2 items",
	"must be number",
	"must NOT have more than 2 items",
	"must match exactly one schema in oneOf"
];
function createError(instancePath, schemaPath, keyword, params, message) {
	return {
		instancePath,
		schemaPath,
		keyword,
		params,
		["message"]: typeof message === "number" ? MESSAGES[message] : message
	};
}
function pushError(errors, error) {
	if (errors === null) {
		return [error];
	}
	errors.push(error);
	return errors;
}
/**
 * Compiled validator for the AuditableItemGraphAuditMode schema.
 */
export const CompiledAuditableItemGraphAuditMode: ICompiledValidator = validate52;
const keyword0 = Object.values(external0["AuditableItemGraphAuditMode"]);

function validate52(
	data,
	{ instancePath = "", parentData, parentDataProperty, rootData = data, dynamicAnchors = {} } = {}
) {
	/*# sourceURL="https://schema.3sixty.global/aig/AuditableItemGraphAuditMode" */ let vErrors =
		null;
	let errors = 0;
	const evaluated0 = validate52.evaluated;
	if (evaluated0.dynamicProps) {
		evaluated0.props = undefined;
	}
	if (evaluated0.dynamicItems) {
		evaluated0.items = undefined;
	}
	if (!keyword0.includes(data)) {
		for (let i0 = 0; i0 < keyword0.length; i0++) {
			vErrors = pushError(
				vErrors,
				createError(
					instancePath,
					"#/anyOf" + "/" + i0 + "/const",
					"const",
					{ allowedValue: keyword0[i0] },
					"must be equal to constant"
				)
			);
			errors++;
		}
		vErrors = pushError(
			vErrors,
			createError(instancePath, "#/anyOf", "anyOf", {}, "must match a schema in anyOf")
		);
		errors++;
	}
	validate52.errors = vErrors;
	return errors === 0;
}
validate52.evaluated = { dynamicProps: false, dynamicItems: false };

/**
 * Compiled validator for the AuditableItemGraphAlias schema.
 */
export const CompiledAuditableItemGraphAlias: ICompiledValidator = validate53;

function validate54(
	data,
	{ instancePath = "", parentData, parentDataProperty, rootData = data, dynamicAnchors = {} } = {}
) {
	/*# sourceURL="https://schema.3sixty.global/aig/AuditableItemGraphAuditedElement" */ let vErrors =
		null;
	let errors = 0;
	const evaluated0 = validate54.evaluated;
	if (evaluated0.dynamicProps) {
		evaluated0.props = undefined;
	}
	if (evaluated0.dynamicItems) {
		evaluated0.items = undefined;
	}
	if (data && typeof data == "object" && !Array.isArray(data)) {
		if (data.id !== undefined) {
			if (typeof data.id !== "string") {
				const err0 = createError(
					instancePath + "/id",
					"#/properties/id/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err0);
				errors++;
			}
		}
		if (data.dateCreated !== undefined) {
			if (typeof data.dateCreated !== "string") {
				const err1 = createError(
					instancePath + "/dateCreated",
					"#/properties/dateCreated/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err1);
				errors++;
			}
		}
		if (data.dateModified !== undefined) {
			if (typeof data.dateModified !== "string") {
				const err2 = createError(
					instancePath + "/dateModified",
					"#/properties/dateModified/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err2);
				errors++;
			}
		}
		if (data.dateDeleted !== undefined) {
			if (typeof data.dateDeleted !== "string") {
				const err3 = createError(
					instancePath + "/dateDeleted",
					"#/properties/dateDeleted/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err3);
				errors++;
			}
		}
	} else {
		const err4 = createError(instancePath, "#/type", "type", { type: "object" }, 1);
		vErrors = pushError(vErrors, err4);
		errors++;
	}
	validate54.errors = vErrors;
	return errors === 0;
}
validate54.evaluated = {
	props: { id: true, dateCreated: true, dateModified: true, dateDeleted: true },
	dynamicProps: false,
	dynamicItems: false
};

const keyword1 = external1["CompiledJsonLdContextDefinitionElement"];
const keyword2 = external1["CompiledJsonLdNodeObject"];

function validate53(
	data,
	{ instancePath = "", parentData, parentDataProperty, rootData = data, dynamicAnchors = {} } = {}
) {
	/*# sourceURL="https://schema.3sixty.global/aig/AuditableItemGraphAlias" */ let vErrors = null;
	let errors = 0;
	const evaluated0 = validate53.evaluated;
	if (evaluated0.dynamicProps) {
		evaluated0.props = undefined;
	}
	if (evaluated0.dynamicItems) {
		evaluated0.items = undefined;
	}
	if (
		!validate54(data, { instancePath, parentData, parentDataProperty, rootData, dynamicAnchors })
	) {
		vErrors = vErrors === null ? validate54.errors : vErrors.concat(validate54.errors);
		errors = vErrors.length;
	}
	if (data && typeof data == "object" && !Array.isArray(data)) {
		if (data.id === undefined) {
			const err0 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "id" },
				"must have required property '" + "id" + "'"
			);
			vErrors = pushError(vErrors, err0);
			errors++;
		}
		if (data.type === undefined) {
			const err1 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "type" },
				"must have required property '" + "type" + "'"
			);
			vErrors = pushError(vErrors, err1);
			errors++;
		}
		if (data["@context"] !== undefined) {
			let data0 = data["@context"];
			const _errs3 = errors;
			let valid2 = false;
			const _errs4 = errors;
			if ("https://schema.3sixty.global/aig/" !== data0) {
				const err2 = createError(
					instancePath + "/@context",
					"#/properties/%40context/anyOf/0/const",
					"const",
					{ allowedValue: "https://schema.3sixty.global/aig/" },
					2
				);
				vErrors = pushError(vErrors, err2);
				errors++;
			}
			var _valid0 = _errs4 === errors;
			valid2 = valid2 || _valid0;
			const _errs5 = errors;
			if (Array.isArray(data0)) {
				if (data0.length < 1) {
					const err3 = createError(
						instancePath + "/@context",
						"#/properties/%40context/anyOf/1/minItems",
						"minItems",
						{ limit: 1 },
						3
					);
					vErrors = pushError(vErrors, err3);
					errors++;
				}
				const len0 = data0.length;
				if (len0 > 0) {
					if ("https://schema.3sixty.global/aig/" !== data0[0]) {
						const err4 = createError(
							instancePath + "/@context/0",
							"#/properties/%40context/anyOf/1/prefixItems/0/const",
							"const",
							{ allowedValue: "https://schema.3sixty.global/aig/" },
							2
						);
						vErrors = pushError(vErrors, err4);
						errors++;
					}
				}
				const len1 = data0.length;
				var valid4 = len1 <= 1;
				if (!valid4) {
					for (let i0 = 1; i0 < len1; i0++) {
						const _errs8 = errors;
						if (
							!keyword1(data0[i0], {
								instancePath: instancePath + "/@context/" + i0,
								parentData: data0,
								parentDataProperty: i0,
								rootData,
								dynamicAnchors
							})
						) {
							vErrors = vErrors === null ? keyword1.errors : vErrors.concat(keyword1.errors);
							errors = vErrors.length;
						}
						var valid4 = _errs8 === errors;
					}
				}
			} else {
				const err5 = createError(
					instancePath + "/@context",
					"#/properties/%40context/anyOf/1/type",
					"type",
					{ type: "array" },
					4
				);
				vErrors = pushError(vErrors, err5);
				errors++;
			}
			var _valid0 = _errs5 === errors;
			valid2 = valid2 || _valid0;
			if (!valid2) {
				const err6 = createError(
					instancePath + "/@context",
					"#/properties/%40context/anyOf",
					"anyOf",
					{},
					5
				);
				vErrors = pushError(vErrors, err6);
				errors++;
			} else {
				errors = _errs3;
				if (vErrors !== null) {
					if (_errs3) {
						vErrors.length = _errs3;
					} else {
						vErrors = null;
					}
				}
			}
		}
		if (data.id !== undefined) {
			if (typeof data.id !== "string") {
				const err7 = createError(
					instancePath + "/id",
					"#/properties/id/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err7);
				errors++;
			}
		}
		if (data.type !== undefined) {
			if ("AuditableItemGraphAlias" !== data.type) {
				const err8 = createError(
					instancePath + "/type",
					"#/properties/type/const",
					"const",
					{ allowedValue: "AuditableItemGraphAlias" },
					2
				);
				vErrors = pushError(vErrors, err8);
				errors++;
			}
		}
		if (data.annotationObject !== undefined) {
			if (
				!keyword2(data.annotationObject, {
					instancePath: instancePath + "/annotationObject",
					parentData: data,
					parentDataProperty: "annotationObject",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword2.errors : vErrors.concat(keyword2.errors);
				errors = vErrors.length;
			}
		}
		if (data.aliasFormat !== undefined) {
			if (typeof data.aliasFormat !== "string") {
				const err9 = createError(
					instancePath + "/aliasFormat",
					"#/properties/aliasFormat/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err9);
				errors++;
			}
		}
		if (data.unique !== undefined) {
			if (typeof data.unique !== "boolean") {
				const err10 = createError(
					instancePath + "/unique",
					"#/properties/unique/type",
					"type",
					{ type: "boolean" },
					6
				);
				vErrors = pushError(vErrors, err10);
				errors++;
			}
		}
	} else {
		const err11 = createError(instancePath, "#/type", "type", { type: "object" }, 1);
		vErrors = pushError(vErrors, err11);
		errors++;
	}
	validate53.errors = vErrors;
	return errors === 0;
}
validate53.evaluated = {
	props: {
		"@context": true,
		id: true,
		type: true,
		annotationObject: true,
		aliasFormat: true,
		unique: true,
		dateCreated: true,
		dateModified: true,
		dateDeleted: true
	},
	dynamicProps: false,
	dynamicItems: false
};

/**
 * Compiled validator for the AuditableItemGraphAuditedElement schema.
 */
export const CompiledAuditableItemGraphAuditedElement: ICompiledValidator = validate54;

/**
 * Compiled validator for the AuditableItemGraphChangeset schema.
 */
export const CompiledAuditableItemGraphChangeset: ICompiledValidator = validate56;
const keyword5 = external2["CompiledImmutableProofVerification"];

function validate57(
	data,
	{ instancePath = "", parentData, parentDataProperty, rootData = data, dynamicAnchors = {} } = {}
) {
	/*# sourceURL="https://schema.3sixty.global/aig/AuditableItemGraphPatchOperation" */ let vErrors =
		null;
	let errors = 0;
	const evaluated0 = validate57.evaluated;
	if (evaluated0.dynamicProps) {
		evaluated0.props = undefined;
	}
	if (evaluated0.dynamicItems) {
		evaluated0.items = undefined;
	}
	if (data && typeof data == "object" && !Array.isArray(data)) {
		if (data.type === undefined) {
			const err0 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "type" },
				"must have required property '" + "type" + "'"
			);
			vErrors = pushError(vErrors, err0);
			errors++;
		}
		if (data.patchOperation === undefined) {
			const err1 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "patchOperation" },
				"must have required property '" + "patchOperation" + "'"
			);
			vErrors = pushError(vErrors, err1);
			errors++;
		}
		if (data.patchPath === undefined) {
			const err2 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "patchPath" },
				"must have required property '" + "patchPath" + "'"
			);
			vErrors = pushError(vErrors, err2);
			errors++;
		}
		if (data["@context"] !== undefined) {
			let data0 = data["@context"];
			const _errs2 = errors;
			let valid1 = false;
			const _errs3 = errors;
			if ("https://schema.3sixty.global/aig/" !== data0) {
				const err3 = createError(
					instancePath + "/@context",
					"#/properties/%40context/anyOf/0/const",
					"const",
					{ allowedValue: "https://schema.3sixty.global/aig/" },
					2
				);
				vErrors = pushError(vErrors, err3);
				errors++;
			}
			var _valid0 = _errs3 === errors;
			valid1 = valid1 || _valid0;
			const _errs4 = errors;
			if (Array.isArray(data0)) {
				if (data0.length < 1) {
					const err4 = createError(
						instancePath + "/@context",
						"#/properties/%40context/anyOf/1/minItems",
						"minItems",
						{ limit: 1 },
						3
					);
					vErrors = pushError(vErrors, err4);
					errors++;
				}
				const len0 = data0.length;
				if (len0 > 0) {
					if ("https://schema.3sixty.global/aig/" !== data0[0]) {
						const err5 = createError(
							instancePath + "/@context/0",
							"#/properties/%40context/anyOf/1/prefixItems/0/const",
							"const",
							{ allowedValue: "https://schema.3sixty.global/aig/" },
							2
						);
						vErrors = pushError(vErrors, err5);
						errors++;
					}
				}
				const len1 = data0.length;
				var valid3 = len1 <= 1;
				if (!valid3) {
					for (let i0 = 1; i0 < len1; i0++) {
						const _errs7 = errors;
						if (
							!keyword1(data0[i0], {
								instancePath: instancePath + "/@context/" + i0,
								parentData: data0,
								parentDataProperty: i0,
								rootData,
								dynamicAnchors
							})
						) {
							vErrors = vErrors === null ? keyword1.errors : vErrors.concat(keyword1.errors);
							errors = vErrors.length;
						}
						var valid3 = _errs7 === errors;
					}
				}
			} else {
				const err6 = createError(
					instancePath + "/@context",
					"#/properties/%40context/anyOf/1/type",
					"type",
					{ type: "array" },
					4
				);
				vErrors = pushError(vErrors, err6);
				errors++;
			}
			var _valid0 = _errs4 === errors;
			valid1 = valid1 || _valid0;
			if (!valid1) {
				const err7 = createError(
					instancePath + "/@context",
					"#/properties/%40context/anyOf",
					"anyOf",
					{},
					5
				);
				vErrors = pushError(vErrors, err7);
				errors++;
			} else {
				errors = _errs2;
				if (vErrors !== null) {
					if (_errs2) {
						vErrors.length = _errs2;
					} else {
						vErrors = null;
					}
				}
			}
		}
		if (data.type !== undefined) {
			if ("AuditableItemGraphPatchOperation" !== data.type) {
				const err8 = createError(
					instancePath + "/type",
					"#/properties/type/const",
					"const",
					{ allowedValue: "AuditableItemGraphPatchOperation" },
					2
				);
				vErrors = pushError(vErrors, err8);
				errors++;
			}
		}
		if (data.patchOperation !== undefined) {
			let data4 = data.patchOperation;
			const _errs10 = errors;
			let valid4 = false;
			const _errs11 = errors;
			if ("add" !== data4) {
				const err9 = createError(
					instancePath + "/patchOperation",
					"#/properties/patchOperation/anyOf/0/const",
					"const",
					{ allowedValue: "add" },
					2
				);
				vErrors = pushError(vErrors, err9);
				errors++;
			}
			var _valid1 = _errs11 === errors;
			valid4 = valid4 || _valid1;
			const _errs12 = errors;
			if ("remove" !== data4) {
				const err10 = createError(
					instancePath + "/patchOperation",
					"#/properties/patchOperation/anyOf/1/const",
					"const",
					{ allowedValue: "remove" },
					2
				);
				vErrors = pushError(vErrors, err10);
				errors++;
			}
			var _valid1 = _errs12 === errors;
			valid4 = valid4 || _valid1;
			const _errs13 = errors;
			if ("replace" !== data4) {
				const err11 = createError(
					instancePath + "/patchOperation",
					"#/properties/patchOperation/anyOf/2/const",
					"const",
					{ allowedValue: "replace" },
					2
				);
				vErrors = pushError(vErrors, err11);
				errors++;
			}
			var _valid1 = _errs13 === errors;
			valid4 = valid4 || _valid1;
			const _errs14 = errors;
			if ("move" !== data4) {
				const err12 = createError(
					instancePath + "/patchOperation",
					"#/properties/patchOperation/anyOf/3/const",
					"const",
					{ allowedValue: "move" },
					2
				);
				vErrors = pushError(vErrors, err12);
				errors++;
			}
			var _valid1 = _errs14 === errors;
			valid4 = valid4 || _valid1;
			const _errs15 = errors;
			if ("copy" !== data4) {
				const err13 = createError(
					instancePath + "/patchOperation",
					"#/properties/patchOperation/anyOf/4/const",
					"const",
					{ allowedValue: "copy" },
					2
				);
				vErrors = pushError(vErrors, err13);
				errors++;
			}
			var _valid1 = _errs15 === errors;
			valid4 = valid4 || _valid1;
			const _errs16 = errors;
			if ("test" !== data4) {
				const err14 = createError(
					instancePath + "/patchOperation",
					"#/properties/patchOperation/anyOf/5/const",
					"const",
					{ allowedValue: "test" },
					2
				);
				vErrors = pushError(vErrors, err14);
				errors++;
			}
			var _valid1 = _errs16 === errors;
			valid4 = valid4 || _valid1;
			if (!valid4) {
				const err15 = createError(
					instancePath + "/patchOperation",
					"#/properties/patchOperation/anyOf",
					"anyOf",
					{},
					5
				);
				vErrors = pushError(vErrors, err15);
				errors++;
			} else {
				errors = _errs10;
				if (vErrors !== null) {
					if (_errs10) {
						vErrors.length = _errs10;
					} else {
						vErrors = null;
					}
				}
			}
		}
		if (data.patchPath !== undefined) {
			if (typeof data.patchPath !== "string") {
				const err16 = createError(
					instancePath + "/patchPath",
					"#/properties/patchPath/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err16);
				errors++;
			}
		}
		if (data.patchFrom !== undefined) {
			if (typeof data.patchFrom !== "string") {
				const err17 = createError(
					instancePath + "/patchFrom",
					"#/properties/patchFrom/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err17);
				errors++;
			}
		}
	} else {
		const err18 = createError(instancePath, "#/type", "type", { type: "object" }, 1);
		vErrors = pushError(vErrors, err18);
		errors++;
	}
	validate57.errors = vErrors;
	return errors === 0;
}
validate57.evaluated = {
	props: {
		"@context": true,
		type: true,
		patchOperation: true,
		patchPath: true,
		patchFrom: true,
		patchValue: true
	},
	dynamicProps: false,
	dynamicItems: false
};

function validate56(
	data,
	{ instancePath = "", parentData, parentDataProperty, rootData = data, dynamicAnchors = {} } = {}
) {
	/*# sourceURL="https://schema.3sixty.global/aig/AuditableItemGraphChangeset" */ let vErrors =
		null;
	let errors = 0;
	const evaluated0 = validate56.evaluated;
	if (evaluated0.dynamicProps) {
		evaluated0.props = undefined;
	}
	if (evaluated0.dynamicItems) {
		evaluated0.items = undefined;
	}
	if (data && typeof data == "object" && !Array.isArray(data)) {
		if (data.type === undefined) {
			const err0 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "type" },
				"must have required property '" + "type" + "'"
			);
			vErrors = pushError(vErrors, err0);
			errors++;
		}
		if (data.id === undefined) {
			const err1 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "id" },
				"must have required property '" + "id" + "'"
			);
			vErrors = pushError(vErrors, err1);
			errors++;
		}
		if (data.dateCreated === undefined) {
			const err2 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "dateCreated" },
				"must have required property '" + "dateCreated" + "'"
			);
			vErrors = pushError(vErrors, err2);
			errors++;
		}
		if (data.patches === undefined) {
			const err3 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "patches" },
				"must have required property '" + "patches" + "'"
			);
			vErrors = pushError(vErrors, err3);
			errors++;
		}
		if (data["@context"] !== undefined) {
			let data0 = data["@context"];
			if (Array.isArray(data0)) {
				if (data0.length < 2) {
					const err4 = createError(
						instancePath + "/@context",
						"#/properties/%40context/minItems",
						"minItems",
						{ limit: 2 },
						7
					);
					vErrors = pushError(vErrors, err4);
					errors++;
				}
				const len0 = data0.length;
				if (len0 > 0) {
					if ("https://schema.3sixty.global/aig/" !== data0[0]) {
						const err5 = createError(
							instancePath + "/@context/0",
							"#/properties/%40context/prefixItems/0/const",
							"const",
							{ allowedValue: "https://schema.3sixty.global/aig/" },
							2
						);
						vErrors = pushError(vErrors, err5);
						errors++;
					}
				}
				if (len0 > 1) {
					if ("https://schema.3sixty.global/common/" !== data0[1]) {
						const err6 = createError(
							instancePath + "/@context/1",
							"#/properties/%40context/prefixItems/1/const",
							"const",
							{ allowedValue: "https://schema.3sixty.global/common/" },
							2
						);
						vErrors = pushError(vErrors, err6);
						errors++;
					}
				}
				const len1 = data0.length;
				var valid2 = len1 <= 2;
				if (!valid2) {
					for (let i0 = 2; i0 < len1; i0++) {
						const _errs5 = errors;
						if (
							!keyword1(data0[i0], {
								instancePath: instancePath + "/@context/" + i0,
								parentData: data0,
								parentDataProperty: i0,
								rootData,
								dynamicAnchors
							})
						) {
							vErrors = vErrors === null ? keyword1.errors : vErrors.concat(keyword1.errors);
							errors = vErrors.length;
						}
						var valid2 = _errs5 === errors;
					}
				}
			} else {
				const err7 = createError(
					instancePath + "/@context",
					"#/properties/%40context/type",
					"type",
					{ type: "array" },
					4
				);
				vErrors = pushError(vErrors, err7);
				errors++;
			}
		}
		if (data.type !== undefined) {
			if ("AuditableItemGraphChangeset" !== data.type) {
				const err8 = createError(
					instancePath + "/type",
					"#/properties/type/const",
					"const",
					{ allowedValue: "AuditableItemGraphChangeset" },
					2
				);
				vErrors = pushError(vErrors, err8);
				errors++;
			}
		}
		if (data.id !== undefined) {
			if (typeof data.id !== "string") {
				const err9 = createError(
					instancePath + "/id",
					"#/properties/id/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err9);
				errors++;
			}
		}
		if (data.dateCreated !== undefined) {
			if (typeof data.dateCreated !== "string") {
				const err10 = createError(
					instancePath + "/dateCreated",
					"#/properties/dateCreated/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err10);
				errors++;
			}
		}
		if (data.userIdentity !== undefined) {
			if (typeof data.userIdentity !== "string") {
				const err11 = createError(
					instancePath + "/userIdentity",
					"#/properties/userIdentity/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err11);
				errors++;
			}
		}
		if (data.patches !== undefined) {
			let data8 = data.patches;
			if (Array.isArray(data8)) {
				const len2 = data8.length;
				for (let i1 = 0; i1 < len2; i1++) {
					if (
						!validate57(data8[i1], {
							instancePath: instancePath + "/patches/" + i1,
							parentData: data8,
							parentDataProperty: i1,
							rootData,
							dynamicAnchors
						})
					) {
						vErrors = vErrors === null ? validate57.errors : vErrors.concat(validate57.errors);
						errors = vErrors.length;
					}
				}
			} else {
				const err12 = createError(
					instancePath + "/patches",
					"#/properties/patches/type",
					"type",
					{ type: "array" },
					4
				);
				vErrors = pushError(vErrors, err12);
				errors++;
			}
		}
		if (data.proofId !== undefined) {
			if (typeof data.proofId !== "string") {
				const err13 = createError(
					instancePath + "/proofId",
					"#/properties/proofId/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err13);
				errors++;
			}
		}
		if (data.verification !== undefined) {
			if (
				!keyword5(data.verification, {
					instancePath: instancePath + "/verification",
					parentData: data,
					parentDataProperty: "verification",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword5.errors : vErrors.concat(keyword5.errors);
				errors = vErrors.length;
			}
		}
		if (data.version !== undefined) {
			let data12 = data.version;
			if (!(typeof data12 == "number" && isFinite(data12))) {
				const err14 = createError(
					instancePath + "/version",
					"#/properties/version/type",
					"type",
					{ type: "number" },
					8
				);
				vErrors = pushError(vErrors, err14);
				errors++;
			}
		}
	} else {
		const err15 = createError(instancePath, "#/type", "type", { type: "object" }, 1);
		vErrors = pushError(vErrors, err15);
		errors++;
	}
	validate56.errors = vErrors;
	return errors === 0;
}
validate56.evaluated = {
	props: {
		"@context": true,
		type: true,
		id: true,
		dateCreated: true,
		userIdentity: true,
		patches: true,
		proofId: true,
		verification: true,
		version: true
	},
	dynamicProps: false,
	dynamicItems: false
};

/**
 * Compiled validator for the AuditableItemGraphChangesetList schema.
 */
export const CompiledAuditableItemGraphChangesetList: ICompiledValidator = validate59;

function validate59(
	data,
	{ instancePath = "", parentData, parentDataProperty, rootData = data, dynamicAnchors = {} } = {}
) {
	/*# sourceURL="https://schema.3sixty.global/aig/AuditableItemGraphChangesetList" */ let vErrors =
		null;
	let errors = 0;
	const evaluated0 = validate59.evaluated;
	if (evaluated0.dynamicProps) {
		evaluated0.props = undefined;
	}
	if (evaluated0.dynamicItems) {
		evaluated0.items = undefined;
	}
	if (data && typeof data == "object" && !Array.isArray(data)) {
		if (data["@context"] === undefined) {
			const err0 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "@context" },
				"must have required property '" + "@context" + "'"
			);
			vErrors = pushError(vErrors, err0);
			errors++;
		}
		if (data.type === undefined) {
			const err1 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "type" },
				"must have required property '" + "type" + "'"
			);
			vErrors = pushError(vErrors, err1);
			errors++;
		}
		if (data.itemListElement === undefined) {
			const err2 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "itemListElement" },
				"must have required property '" + "itemListElement" + "'"
			);
			vErrors = pushError(vErrors, err2);
			errors++;
		}
		if (data["@context"] !== undefined) {
			let data0 = data["@context"];
			if (Array.isArray(data0)) {
				if (data0.length < 2) {
					const err3 = createError(
						instancePath + "/@context",
						"#/properties/%40context/minItems",
						"minItems",
						{ limit: 2 },
						7
					);
					vErrors = pushError(vErrors, err3);
					errors++;
				}
				const len0 = data0.length;
				if (len0 > 0) {
					if ("https://schema.org" !== data0[0]) {
						const err4 = createError(
							instancePath + "/@context/0",
							"#/properties/%40context/prefixItems/0/const",
							"const",
							{ allowedValue: "https://schema.org" },
							2
						);
						vErrors = pushError(vErrors, err4);
						errors++;
					}
				}
				if (len0 > 1) {
					if ("https://schema.3sixty.global/aig/" !== data0[1]) {
						const err5 = createError(
							instancePath + "/@context/1",
							"#/properties/%40context/prefixItems/1/const",
							"const",
							{ allowedValue: "https://schema.3sixty.global/aig/" },
							2
						);
						vErrors = pushError(vErrors, err5);
						errors++;
					}
				}
				const len1 = data0.length;
				var valid2 = len1 <= 2;
				if (!valid2) {
					for (let i0 = 2; i0 < len1; i0++) {
						const _errs5 = errors;
						if (
							!keyword1(data0[i0], {
								instancePath: instancePath + "/@context/" + i0,
								parentData: data0,
								parentDataProperty: i0,
								rootData,
								dynamicAnchors
							})
						) {
							vErrors = vErrors === null ? keyword1.errors : vErrors.concat(keyword1.errors);
							errors = vErrors.length;
						}
						var valid2 = _errs5 === errors;
					}
				}
			} else {
				const err6 = createError(
					instancePath + "/@context",
					"#/properties/%40context/type",
					"type",
					{ type: "array" },
					4
				);
				vErrors = pushError(vErrors, err6);
				errors++;
			}
		}
		if (data.type !== undefined) {
			let data4 = data.type;
			if (Array.isArray(data4)) {
				if (data4.length > 2) {
					const err7 = createError(
						instancePath + "/type",
						"#/properties/type/maxItems",
						"maxItems",
						{ limit: 2 },
						9
					);
					vErrors = pushError(vErrors, err7);
					errors++;
				}
				if (data4.length < 2) {
					const err8 = createError(
						instancePath + "/type",
						"#/properties/type/minItems",
						"minItems",
						{ limit: 2 },
						7
					);
					vErrors = pushError(vErrors, err8);
					errors++;
				}
				const len2 = data4.length;
				if (len2 > 0) {
					if ("ItemList" !== data4[0]) {
						const err9 = createError(
							instancePath + "/type/0",
							"#/properties/type/prefixItems/0/const",
							"const",
							{ allowedValue: "ItemList" },
							2
						);
						vErrors = pushError(vErrors, err9);
						errors++;
					}
				}
				if (len2 > 1) {
					if ("AuditableItemGraphChangesetList" !== data4[1]) {
						const err10 = createError(
							instancePath + "/type/1",
							"#/properties/type/prefixItems/1/const",
							"const",
							{ allowedValue: "AuditableItemGraphChangesetList" },
							2
						);
						vErrors = pushError(vErrors, err10);
						errors++;
					}
				}
				const len3 = data4.length;
				if (!(len3 <= 2)) {
					const err11 = createError(
						instancePath + "/type",
						"#/properties/type/items",
						"items",
						{ limit: 2 },
						9
					);
					vErrors = pushError(vErrors, err11);
					errors++;
				}
			} else {
				const err12 = createError(
					instancePath + "/type",
					"#/properties/type/type",
					"type",
					{ type: "array" },
					4
				);
				vErrors = pushError(vErrors, err12);
				errors++;
			}
		}
		if (data.itemListElement !== undefined) {
			let data7 = data.itemListElement;
			if (Array.isArray(data7)) {
				const len4 = data7.length;
				for (let i1 = 0; i1 < len4; i1++) {
					if (
						!validate56(data7[i1], {
							instancePath: instancePath + "/itemListElement/" + i1,
							parentData: data7,
							parentDataProperty: i1,
							rootData,
							dynamicAnchors
						})
					) {
						vErrors = vErrors === null ? validate56.errors : vErrors.concat(validate56.errors);
						errors = vErrors.length;
					}
				}
			} else {
				const err13 = createError(
					instancePath + "/itemListElement",
					"#/properties/itemListElement/type",
					"type",
					{ type: "array" },
					4
				);
				vErrors = pushError(vErrors, err13);
				errors++;
			}
		}
	} else {
		const err14 = createError(instancePath, "#/type", "type", { type: "object" }, 1);
		vErrors = pushError(vErrors, err14);
		errors++;
	}
	validate59.errors = vErrors;
	return errors === 0;
}
validate59.evaluated = {
	props: { "@context": true, type: true, itemListElement: true },
	dynamicProps: false,
	dynamicItems: false
};

/**
 * Compiled validator for the AuditableItemGraphEdge schema.
 */
export const CompiledAuditableItemGraphEdge: ICompiledValidator = validate61;

function validate61(
	data,
	{ instancePath = "", parentData, parentDataProperty, rootData = data, dynamicAnchors = {} } = {}
) {
	/*# sourceURL="https://schema.3sixty.global/aig/AuditableItemGraphEdge" */ let vErrors = null;
	let errors = 0;
	const evaluated0 = validate61.evaluated;
	if (evaluated0.dynamicProps) {
		evaluated0.props = undefined;
	}
	if (evaluated0.dynamicItems) {
		evaluated0.items = undefined;
	}
	if (
		!validate54(data, { instancePath, parentData, parentDataProperty, rootData, dynamicAnchors })
	) {
		vErrors = vErrors === null ? validate54.errors : vErrors.concat(validate54.errors);
		errors = vErrors.length;
	}
	if (data && typeof data == "object" && !Array.isArray(data)) {
		if (data.targetId === undefined) {
			const err0 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "targetId" },
				"must have required property '" + "targetId" + "'"
			);
			vErrors = pushError(vErrors, err0);
			errors++;
		}
		if (data.type === undefined) {
			const err1 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "type" },
				"must have required property '" + "type" + "'"
			);
			vErrors = pushError(vErrors, err1);
			errors++;
		}
		if (data.edgeRelationships === undefined) {
			const err2 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "edgeRelationships" },
				"must have required property '" + "edgeRelationships" + "'"
			);
			vErrors = pushError(vErrors, err2);
			errors++;
		}
		if (data["@context"] !== undefined) {
			let data0 = data["@context"];
			const _errs3 = errors;
			let valid2 = false;
			const _errs4 = errors;
			if ("https://schema.3sixty.global/aig/" !== data0) {
				const err3 = createError(
					instancePath + "/@context",
					"#/properties/%40context/anyOf/0/const",
					"const",
					{ allowedValue: "https://schema.3sixty.global/aig/" },
					2
				);
				vErrors = pushError(vErrors, err3);
				errors++;
			}
			var _valid0 = _errs4 === errors;
			valid2 = valid2 || _valid0;
			const _errs5 = errors;
			if (Array.isArray(data0)) {
				if (data0.length < 1) {
					const err4 = createError(
						instancePath + "/@context",
						"#/properties/%40context/anyOf/1/minItems",
						"minItems",
						{ limit: 1 },
						3
					);
					vErrors = pushError(vErrors, err4);
					errors++;
				}
				const len0 = data0.length;
				if (len0 > 0) {
					if ("https://schema.3sixty.global/aig/" !== data0[0]) {
						const err5 = createError(
							instancePath + "/@context/0",
							"#/properties/%40context/anyOf/1/prefixItems/0/const",
							"const",
							{ allowedValue: "https://schema.3sixty.global/aig/" },
							2
						);
						vErrors = pushError(vErrors, err5);
						errors++;
					}
				}
				const len1 = data0.length;
				var valid4 = len1 <= 1;
				if (!valid4) {
					for (let i0 = 1; i0 < len1; i0++) {
						const _errs8 = errors;
						if (
							!keyword1(data0[i0], {
								instancePath: instancePath + "/@context/" + i0,
								parentData: data0,
								parentDataProperty: i0,
								rootData,
								dynamicAnchors
							})
						) {
							vErrors = vErrors === null ? keyword1.errors : vErrors.concat(keyword1.errors);
							errors = vErrors.length;
						}
						var valid4 = _errs8 === errors;
					}
				}
			} else {
				const err6 = createError(
					instancePath + "/@context",
					"#/properties/%40context/anyOf/1/type",
					"type",
					{ type: "array" },
					4
				);
				vErrors = pushError(vErrors, err6);
				errors++;
			}
			var _valid0 = _errs5 === errors;
			valid2 = valid2 || _valid0;
			if (!valid2) {
				const err7 = createError(
					instancePath + "/@context",
					"#/properties/%40context/anyOf",
					"anyOf",
					{},
					5
				);
				vErrors = pushError(vErrors, err7);
				errors++;
			} else {
				errors = _errs3;
				if (vErrors !== null) {
					if (_errs3) {
						vErrors.length = _errs3;
					} else {
						vErrors = null;
					}
				}
			}
		}
		if (data.id !== undefined) {
			if (typeof data.id !== "string") {
				const err8 = createError(
					instancePath + "/id",
					"#/properties/id/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err8);
				errors++;
			}
		}
		if (data.targetId !== undefined) {
			if (typeof data.targetId !== "string") {
				const err9 = createError(
					instancePath + "/targetId",
					"#/properties/targetId/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err9);
				errors++;
			}
		}
		if (data.type !== undefined) {
			if ("AuditableItemGraphEdge" !== data.type) {
				const err10 = createError(
					instancePath + "/type",
					"#/properties/type/const",
					"const",
					{ allowedValue: "AuditableItemGraphEdge" },
					2
				);
				vErrors = pushError(vErrors, err10);
				errors++;
			}
		}
		if (data.annotationObject !== undefined) {
			if (
				!keyword2(data.annotationObject, {
					instancePath: instancePath + "/annotationObject",
					parentData: data,
					parentDataProperty: "annotationObject",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword2.errors : vErrors.concat(keyword2.errors);
				errors = vErrors.length;
			}
		}
		if (data.edgeRelationships !== undefined) {
			let data7 = data.edgeRelationships;
			if (Array.isArray(data7)) {
				const len2 = data7.length;
				for (let i1 = 0; i1 < len2; i1++) {
					if (typeof data7[i1] !== "string") {
						const err11 = createError(
							instancePath + "/edgeRelationships/" + i1,
							"#/properties/edgeRelationships/items/type",
							"type",
							{ type: "string" },
							0
						);
						vErrors = pushError(vErrors, err11);
						errors++;
					}
				}
			} else {
				const err12 = createError(
					instancePath + "/edgeRelationships",
					"#/properties/edgeRelationships/type",
					"type",
					{ type: "array" },
					4
				);
				vErrors = pushError(vErrors, err12);
				errors++;
			}
		}
	} else {
		const err13 = createError(instancePath, "#/type", "type", { type: "object" }, 1);
		vErrors = pushError(vErrors, err13);
		errors++;
	}
	validate61.errors = vErrors;
	return errors === 0;
}
validate61.evaluated = {
	props: {
		"@context": true,
		id: true,
		targetId: true,
		type: true,
		annotationObject: true,
		edgeRelationships: true,
		dateCreated: true,
		dateModified: true,
		dateDeleted: true
	},
	dynamicProps: false,
	dynamicItems: false
};

/**
 * Compiled validator for the AuditableItemGraphListPatch schema.
 */
export const CompiledAuditableItemGraphListPatch: ICompiledValidator = validate63;

function validate66(
	data,
	{ instancePath = "", parentData, parentDataProperty, rootData = data, dynamicAnchors = {} } = {}
) {
	/*# sourceURL="https://schema.3sixty.global/aig/AuditableItemGraphResource" */ let vErrors = null;
	let errors = 0;
	const evaluated0 = validate66.evaluated;
	if (evaluated0.dynamicProps) {
		evaluated0.props = undefined;
	}
	if (evaluated0.dynamicItems) {
		evaluated0.items = undefined;
	}
	if (
		!validate54(data, { instancePath, parentData, parentDataProperty, rootData, dynamicAnchors })
	) {
		vErrors = vErrors === null ? validate54.errors : vErrors.concat(validate54.errors);
		errors = vErrors.length;
	}
	if (data && typeof data == "object" && !Array.isArray(data)) {
		if (data.type === undefined) {
			const err0 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "type" },
				"must have required property '" + "type" + "'"
			);
			vErrors = pushError(vErrors, err0);
			errors++;
		}
		if (data["@context"] !== undefined) {
			let data0 = data["@context"];
			const _errs3 = errors;
			let valid2 = false;
			const _errs4 = errors;
			if ("https://schema.3sixty.global/aig/" !== data0) {
				const err1 = createError(
					instancePath + "/@context",
					"#/properties/%40context/anyOf/0/const",
					"const",
					{ allowedValue: "https://schema.3sixty.global/aig/" },
					2
				);
				vErrors = pushError(vErrors, err1);
				errors++;
			}
			var _valid0 = _errs4 === errors;
			valid2 = valid2 || _valid0;
			const _errs5 = errors;
			if (Array.isArray(data0)) {
				if (data0.length < 1) {
					const err2 = createError(
						instancePath + "/@context",
						"#/properties/%40context/anyOf/1/minItems",
						"minItems",
						{ limit: 1 },
						3
					);
					vErrors = pushError(vErrors, err2);
					errors++;
				}
				const len0 = data0.length;
				if (len0 > 0) {
					if ("https://schema.3sixty.global/aig/" !== data0[0]) {
						const err3 = createError(
							instancePath + "/@context/0",
							"#/properties/%40context/anyOf/1/prefixItems/0/const",
							"const",
							{ allowedValue: "https://schema.3sixty.global/aig/" },
							2
						);
						vErrors = pushError(vErrors, err3);
						errors++;
					}
				}
				const len1 = data0.length;
				var valid4 = len1 <= 1;
				if (!valid4) {
					for (let i0 = 1; i0 < len1; i0++) {
						const _errs8 = errors;
						if (
							!keyword1(data0[i0], {
								instancePath: instancePath + "/@context/" + i0,
								parentData: data0,
								parentDataProperty: i0,
								rootData,
								dynamicAnchors
							})
						) {
							vErrors = vErrors === null ? keyword1.errors : vErrors.concat(keyword1.errors);
							errors = vErrors.length;
						}
						var valid4 = _errs8 === errors;
					}
				}
			} else {
				const err4 = createError(
					instancePath + "/@context",
					"#/properties/%40context/anyOf/1/type",
					"type",
					{ type: "array" },
					4
				);
				vErrors = pushError(vErrors, err4);
				errors++;
			}
			var _valid0 = _errs5 === errors;
			valid2 = valid2 || _valid0;
			if (!valid2) {
				const err5 = createError(
					instancePath + "/@context",
					"#/properties/%40context/anyOf",
					"anyOf",
					{},
					5
				);
				vErrors = pushError(vErrors, err5);
				errors++;
			} else {
				errors = _errs3;
				if (vErrors !== null) {
					if (_errs3) {
						vErrors.length = _errs3;
					} else {
						vErrors = null;
					}
				}
			}
		}
		if (data.type !== undefined) {
			if ("AuditableItemGraphResource" !== data.type) {
				const err6 = createError(
					instancePath + "/type",
					"#/properties/type/const",
					"const",
					{ allowedValue: "AuditableItemGraphResource" },
					2
				);
				vErrors = pushError(vErrors, err6);
				errors++;
			}
		}
		if (data.resourceObject !== undefined) {
			if (
				!keyword2(data.resourceObject, {
					instancePath: instancePath + "/resourceObject",
					parentData: data,
					parentDataProperty: "resourceObject",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword2.errors : vErrors.concat(keyword2.errors);
				errors = vErrors.length;
			}
		}
	} else {
		const err7 = createError(instancePath, "#/type", "type", { type: "object" }, 1);
		vErrors = pushError(vErrors, err7);
		errors++;
	}
	validate66.errors = vErrors;
	return errors === 0;
}
validate66.evaluated = {
	props: {
		"@context": true,
		type: true,
		resourceObject: true,
		id: true,
		dateCreated: true,
		dateModified: true,
		dateDeleted: true
	},
	dynamicProps: false,
	dynamicItems: false
};

function validate63(
	data,
	{ instancePath = "", parentData, parentDataProperty, rootData = data, dynamicAnchors = {} } = {}
) {
	/*# sourceURL="https://schema.3sixty.global/aig/AuditableItemGraphListPatch" */ let vErrors =
		null;
	let errors = 0;
	const evaluated0 = validate63.evaluated;
	if (evaluated0.dynamicProps) {
		evaluated0.props = undefined;
	}
	if (evaluated0.dynamicItems) {
		evaluated0.items = undefined;
	}
	if (data && typeof data == "object" && !Array.isArray(data)) {
		if (data.add !== undefined) {
			let data0 = data.add;
			if (Array.isArray(data0)) {
				const len0 = data0.length;
				for (let i0 = 0; i0 < len0; i0++) {
					let data1 = data0[i0];
					const _errs4 = errors;
					let valid3 = false;
					let passing0 = null;
					const _errs5 = errors;
					if (
						!validate61(data1, {
							instancePath: instancePath + "/add/" + i0,
							parentData: data0,
							parentDataProperty: i0,
							rootData,
							dynamicAnchors
						})
					) {
						vErrors = vErrors === null ? validate61.errors : vErrors.concat(validate61.errors);
						errors = vErrors.length;
					}
					var _valid0 = _errs5 === errors;
					if (_valid0) {
						valid3 = true;
						passing0 = 0;
						var props0 = {};
						props0["@context"] = true;
						props0.id = true;
						props0.targetId = true;
						props0.type = true;
						props0.annotationObject = true;
						props0.edgeRelationships = true;
						props0.dateCreated = true;
						props0.dateModified = true;
						props0.dateDeleted = true;
					}
					const _errs6 = errors;
					if (
						!validate53(data1, {
							instancePath: instancePath + "/add/" + i0,
							parentData: data0,
							parentDataProperty: i0,
							rootData,
							dynamicAnchors
						})
					) {
						vErrors = vErrors === null ? validate53.errors : vErrors.concat(validate53.errors);
						errors = vErrors.length;
					}
					var _valid0 = _errs6 === errors;
					if (_valid0 && valid3) {
						valid3 = false;
						passing0 = [passing0, 1];
					} else {
						if (_valid0) {
							valid3 = true;
							passing0 = 1;
							if (props0 !== true) {
								props0 = props0 || {};
								props0["@context"] = true;
								props0.id = true;
								props0.type = true;
								props0.annotationObject = true;
								props0.aliasFormat = true;
								props0.unique = true;
								props0.dateCreated = true;
								props0.dateModified = true;
								props0.dateDeleted = true;
							}
						}
						const _errs7 = errors;
						if (
							!validate66(data1, {
								instancePath: instancePath + "/add/" + i0,
								parentData: data0,
								parentDataProperty: i0,
								rootData,
								dynamicAnchors
							})
						) {
							vErrors = vErrors === null ? validate66.errors : vErrors.concat(validate66.errors);
							errors = vErrors.length;
						}
						var _valid0 = _errs7 === errors;
						if (_valid0 && valid3) {
							valid3 = false;
							passing0 = [passing0, 2];
						} else {
							if (_valid0) {
								valid3 = true;
								passing0 = 2;
								if (props0 !== true) {
									props0 = props0 || {};
									props0["@context"] = true;
									props0.type = true;
									props0.resourceObject = true;
									props0.id = true;
									props0.dateCreated = true;
									props0.dateModified = true;
									props0.dateDeleted = true;
								}
							}
						}
					}
					if (!valid3) {
						const err0 = createError(
							instancePath + "/add/" + i0,
							"#/properties/add/items/oneOf",
							"oneOf",
							{ passingSchemas: passing0 },
							10
						);
						vErrors = pushError(vErrors, err0);
						errors++;
					} else {
						errors = _errs4;
						if (vErrors !== null) {
							if (_errs4) {
								vErrors.length = _errs4;
							} else {
								vErrors = null;
							}
						}
					}
				}
			} else {
				const err1 = createError(
					instancePath + "/add",
					"#/properties/add/type",
					"type",
					{ type: "array" },
					4
				);
				vErrors = pushError(vErrors, err1);
				errors++;
			}
		}
		if (data.remove !== undefined) {
			let data2 = data.remove;
			if (Array.isArray(data2)) {
				const len1 = data2.length;
				for (let i1 = 0; i1 < len1; i1++) {
					if (typeof data2[i1] !== "string") {
						const err2 = createError(
							instancePath + "/remove/" + i1,
							"#/properties/remove/items/type",
							"type",
							{ type: "string" },
							0
						);
						vErrors = pushError(vErrors, err2);
						errors++;
					}
				}
			} else {
				const err3 = createError(
					instancePath + "/remove",
					"#/properties/remove/type",
					"type",
					{ type: "array" },
					4
				);
				vErrors = pushError(vErrors, err3);
				errors++;
			}
		}
	} else {
		const err4 = createError(instancePath, "#/type", "type", { type: "object" }, 1);
		vErrors = pushError(vErrors, err4);
		errors++;
	}
	validate63.errors = vErrors;
	return errors === 0;
}
validate63.evaluated = {
	props: { add: true, remove: true },
	dynamicProps: false,
	dynamicItems: false
};

/**
 * Compiled validator for the AuditableItemGraphPartialVertex schema.
 */
export const CompiledAuditableItemGraphPartialVertex: ICompiledValidator = validate69;

function validate69(
	data,
	{ instancePath = "", parentData, parentDataProperty, rootData = data, dynamicAnchors = {} } = {}
) {
	/*# sourceURL="https://schema.3sixty.global/aig/AuditableItemGraphPartialVertex" */ let vErrors =
		null;
	let errors = 0;
	const evaluated0 = validate69.evaluated;
	if (evaluated0.dynamicProps) {
		evaluated0.props = undefined;
	}
	if (evaluated0.dynamicItems) {
		evaluated0.items = undefined;
	}
	if (data && typeof data == "object" && !Array.isArray(data)) {
		if (data["@context"] === undefined) {
			const err0 = createError(
				instancePath,
				"#/allOf/0/required",
				"required",
				{ missingProperty: "@context" },
				"must have required property '" + "@context" + "'"
			);
			vErrors = pushError(vErrors, err0);
			errors++;
		}
		if (data.dateCreated !== undefined) {
			if (typeof data.dateCreated !== "string") {
				const err1 = createError(
					instancePath + "/dateCreated",
					"#/allOf/0/properties/dateCreated/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err1);
				errors++;
			}
		}
		if (data.dateModified !== undefined) {
			if (typeof data.dateModified !== "string") {
				const err2 = createError(
					instancePath + "/dateModified",
					"#/allOf/0/properties/dateModified/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err2);
				errors++;
			}
		}
		if (data.dateDeleted !== undefined) {
			if (typeof data.dateDeleted !== "string") {
				const err3 = createError(
					instancePath + "/dateDeleted",
					"#/allOf/0/properties/dateDeleted/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err3);
				errors++;
			}
		}
		if (data["@context"] !== undefined) {
			let data3 = data["@context"];
			if (Array.isArray(data3)) {
				if (data3.length < 2) {
					const err4 = createError(
						instancePath + "/@context",
						"#/allOf/0/properties/%40context/minItems",
						"minItems",
						{ limit: 2 },
						7
					);
					vErrors = pushError(vErrors, err4);
					errors++;
				}
				const len0 = data3.length;
				if (len0 > 0) {
					if ("https://schema.3sixty.global/aig/" !== data3[0]) {
						const err5 = createError(
							instancePath + "/@context/0",
							"#/allOf/0/properties/%40context/prefixItems/0/const",
							"const",
							{ allowedValue: "https://schema.3sixty.global/aig/" },
							2
						);
						vErrors = pushError(vErrors, err5);
						errors++;
					}
				}
				if (len0 > 1) {
					if ("https://schema.3sixty.global/common/" !== data3[1]) {
						const err6 = createError(
							instancePath + "/@context/1",
							"#/allOf/0/properties/%40context/prefixItems/1/const",
							"const",
							{ allowedValue: "https://schema.3sixty.global/common/" },
							2
						);
						vErrors = pushError(vErrors, err6);
						errors++;
					}
				}
				const len1 = data3.length;
				var valid3 = len1 <= 2;
				if (!valid3) {
					for (let i0 = 2; i0 < len1; i0++) {
						const _errs15 = errors;
						if (
							!keyword1(data3[i0], {
								instancePath: instancePath + "/@context/" + i0,
								parentData: data3,
								parentDataProperty: i0,
								rootData,
								dynamicAnchors
							})
						) {
							vErrors = vErrors === null ? keyword1.errors : vErrors.concat(keyword1.errors);
							errors = vErrors.length;
						}
						var valid3 = _errs15 === errors;
					}
				}
			} else {
				const err7 = createError(
					instancePath + "/@context",
					"#/allOf/0/properties/%40context/type",
					"type",
					{ type: "array" },
					4
				);
				vErrors = pushError(vErrors, err7);
				errors++;
			}
		}
		if (data.organizationIdentity !== undefined) {
			if (typeof data.organizationIdentity !== "string") {
				const err8 = createError(
					instancePath + "/organizationIdentity",
					"#/allOf/0/properties/organizationIdentity/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err8);
				errors++;
			}
		}
		if (data.auditMode !== undefined) {
			if (
				!validate52(data.auditMode, {
					instancePath: instancePath + "/auditMode",
					parentData: data,
					parentDataProperty: "auditMode",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? validate52.errors : vErrors.concat(validate52.errors);
				errors = vErrors.length;
			}
		}
		if (data.annotationObject !== undefined) {
			if (
				!keyword2(data.annotationObject, {
					instancePath: instancePath + "/annotationObject",
					parentData: data,
					parentDataProperty: "annotationObject",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword2.errors : vErrors.concat(keyword2.errors);
				errors = vErrors.length;
			}
		}
		if (data.verified !== undefined) {
			if (typeof data.verified !== "boolean") {
				const err9 = createError(
					instancePath + "/verified",
					"#/allOf/0/properties/verified/type",
					"type",
					{ type: "boolean" },
					6
				);
				vErrors = pushError(vErrors, err9);
				errors++;
			}
		}
		if (data.version !== undefined) {
			let data11 = data.version;
			if (!(typeof data11 == "number" && isFinite(data11))) {
				const err10 = createError(
					instancePath + "/version",
					"#/allOf/0/properties/version/type",
					"type",
					{ type: "number" },
					8
				);
				vErrors = pushError(vErrors, err10);
				errors++;
			}
		}
	} else {
		const err11 = createError(instancePath, "#/allOf/0/type", "type", { type: "object" }, 1);
		vErrors = pushError(vErrors, err11);
		errors++;
	}
	if (data && typeof data == "object" && !Array.isArray(data)) {
		if (data.id === undefined) {
			const err12 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "id" },
				"must have required property '" + "id" + "'"
			);
			vErrors = pushError(vErrors, err12);
			errors++;
		}
		if (data["@context"] === undefined) {
			const err13 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "@context" },
				"must have required property '" + "@context" + "'"
			);
			vErrors = pushError(vErrors, err13);
			errors++;
		}
		if (data.id !== undefined) {
			if (typeof data.id !== "string") {
				const err14 = createError(
					instancePath + "/id",
					"#/properties/id/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err14);
				errors++;
			}
		}
		if (data["@context"] !== undefined) {
			let data13 = data["@context"];
			if (Array.isArray(data13)) {
				if (data13.length < 2) {
					const err15 = createError(
						instancePath + "/@context",
						"#/properties/%40context/minItems",
						"minItems",
						{ limit: 2 },
						7
					);
					vErrors = pushError(vErrors, err15);
					errors++;
				}
				const len2 = data13.length;
				if (len2 > 0) {
					if ("https://schema.3sixty.global/aig/" !== data13[0]) {
						const err16 = createError(
							instancePath + "/@context/0",
							"#/properties/%40context/prefixItems/0/const",
							"const",
							{ allowedValue: "https://schema.3sixty.global/aig/" },
							2
						);
						vErrors = pushError(vErrors, err16);
						errors++;
					}
				}
				if (len2 > 1) {
					if ("https://schema.3sixty.global/common/" !== data13[1]) {
						const err17 = createError(
							instancePath + "/@context/1",
							"#/properties/%40context/prefixItems/1/const",
							"const",
							{ allowedValue: "https://schema.3sixty.global/common/" },
							2
						);
						vErrors = pushError(vErrors, err17);
						errors++;
					}
				}
				const len3 = data13.length;
				var valid6 = len3 <= 2;
				if (!valid6) {
					for (let i1 = 2; i1 < len3; i1++) {
						const _errs35 = errors;
						if (
							!keyword1(data13[i1], {
								instancePath: instancePath + "/@context/" + i1,
								parentData: data13,
								parentDataProperty: i1,
								rootData,
								dynamicAnchors
							})
						) {
							vErrors = vErrors === null ? keyword1.errors : vErrors.concat(keyword1.errors);
							errors = vErrors.length;
						}
						var valid6 = _errs35 === errors;
					}
				}
			} else {
				const err18 = createError(
					instancePath + "/@context",
					"#/properties/%40context/type",
					"type",
					{ type: "array" },
					4
				);
				vErrors = pushError(vErrors, err18);
				errors++;
			}
		}
		if (data.type !== undefined) {
			if ("AuditableItemGraphVertex" !== data.type) {
				const err19 = createError(
					instancePath + "/type",
					"#/properties/type/const",
					"const",
					{ allowedValue: "AuditableItemGraphVertex" },
					2
				);
				vErrors = pushError(vErrors, err19);
				errors++;
			}
		}
		if (data.aliasPatches !== undefined) {
			if (
				!validate63(data.aliasPatches, {
					instancePath: instancePath + "/aliasPatches",
					parentData: data,
					parentDataProperty: "aliasPatches",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? validate63.errors : vErrors.concat(validate63.errors);
				errors = vErrors.length;
			}
		}
		if (data.resourcePatches !== undefined) {
			if (
				!validate63(data.resourcePatches, {
					instancePath: instancePath + "/resourcePatches",
					parentData: data,
					parentDataProperty: "resourcePatches",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? validate63.errors : vErrors.concat(validate63.errors);
				errors = vErrors.length;
			}
		}
		if (data.edgePatches !== undefined) {
			if (
				!validate63(data.edgePatches, {
					instancePath: instancePath + "/edgePatches",
					parentData: data,
					parentDataProperty: "edgePatches",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? validate63.errors : vErrors.concat(validate63.errors);
				errors = vErrors.length;
			}
		}
	} else {
		const err20 = createError(instancePath, "#/type", "type", { type: "object" }, 1);
		vErrors = pushError(vErrors, err20);
		errors++;
	}
	validate69.errors = vErrors;
	return errors === 0;
}
validate69.evaluated = {
	props: {
		id: true,
		"@context": true,
		type: true,
		aliasPatches: true,
		resourcePatches: true,
		edgePatches: true,
		dateCreated: true,
		dateModified: true,
		dateDeleted: true,
		organizationIdentity: true,
		auditMode: true,
		annotationObject: true,
		verified: true,
		version: true
	},
	dynamicProps: false,
	dynamicItems: false
};

/**
 * Compiled validator for the AuditableItemGraphPatchOperation schema.
 */
export const CompiledAuditableItemGraphPatchOperation: ICompiledValidator = validate57;

/**
 * Compiled validator for the AuditableItemGraphResource schema.
 */
export const CompiledAuditableItemGraphResource: ICompiledValidator = validate66;

/**
 * Compiled validator for the AuditableItemGraphVertex schema.
 */
export const CompiledAuditableItemGraphVertex: ICompiledValidator = validate74;

function validate74(
	data,
	{ instancePath = "", parentData, parentDataProperty, rootData = data, dynamicAnchors = {} } = {}
) {
	/*# sourceURL="https://schema.3sixty.global/aig/AuditableItemGraphVertex" */ let vErrors = null;
	let errors = 0;
	const evaluated0 = validate74.evaluated;
	if (evaluated0.dynamicProps) {
		evaluated0.props = undefined;
	}
	if (evaluated0.dynamicItems) {
		evaluated0.items = undefined;
	}
	if (data && typeof data == "object" && !Array.isArray(data)) {
		if (data.dateCreated !== undefined) {
			if (typeof data.dateCreated !== "string") {
				const err0 = createError(
					instancePath + "/dateCreated",
					"#/allOf/0/properties/dateCreated/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err0);
				errors++;
			}
		}
		if (data.dateModified !== undefined) {
			if (typeof data.dateModified !== "string") {
				const err1 = createError(
					instancePath + "/dateModified",
					"#/allOf/0/properties/dateModified/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err1);
				errors++;
			}
		}
		if (data.dateDeleted !== undefined) {
			if (typeof data.dateDeleted !== "string") {
				const err2 = createError(
					instancePath + "/dateDeleted",
					"#/allOf/0/properties/dateDeleted/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err2);
				errors++;
			}
		}
	} else {
		const err3 = createError(instancePath, "#/allOf/0/type", "type", { type: "object" }, 1);
		vErrors = pushError(vErrors, err3);
		errors++;
	}
	if (data && typeof data == "object" && !Array.isArray(data)) {
		if (data["@context"] === undefined) {
			const err4 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "@context" },
				"must have required property '" + "@context" + "'"
			);
			vErrors = pushError(vErrors, err4);
			errors++;
		}
		if (data.id === undefined) {
			const err5 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "id" },
				"must have required property '" + "id" + "'"
			);
			vErrors = pushError(vErrors, err5);
			errors++;
		}
		if (data.type === undefined) {
			const err6 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "type" },
				"must have required property '" + "type" + "'"
			);
			vErrors = pushError(vErrors, err6);
			errors++;
		}
		if (data["@context"] !== undefined) {
			let data3 = data["@context"];
			if (Array.isArray(data3)) {
				if (data3.length < 2) {
					const err7 = createError(
						instancePath + "/@context",
						"#/properties/%40context/minItems",
						"minItems",
						{ limit: 2 },
						7
					);
					vErrors = pushError(vErrors, err7);
					errors++;
				}
				const len0 = data3.length;
				if (len0 > 0) {
					if ("https://schema.3sixty.global/aig/" !== data3[0]) {
						const err8 = createError(
							instancePath + "/@context/0",
							"#/properties/%40context/prefixItems/0/const",
							"const",
							{ allowedValue: "https://schema.3sixty.global/aig/" },
							2
						);
						vErrors = pushError(vErrors, err8);
						errors++;
					}
				}
				if (len0 > 1) {
					if ("https://schema.3sixty.global/common/" !== data3[1]) {
						const err9 = createError(
							instancePath + "/@context/1",
							"#/properties/%40context/prefixItems/1/const",
							"const",
							{ allowedValue: "https://schema.3sixty.global/common/" },
							2
						);
						vErrors = pushError(vErrors, err9);
						errors++;
					}
				}
				const len1 = data3.length;
				var valid4 = len1 <= 2;
				if (!valid4) {
					for (let i0 = 2; i0 < len1; i0++) {
						const _errs14 = errors;
						if (
							!keyword1(data3[i0], {
								instancePath: instancePath + "/@context/" + i0,
								parentData: data3,
								parentDataProperty: i0,
								rootData,
								dynamicAnchors
							})
						) {
							vErrors = vErrors === null ? keyword1.errors : vErrors.concat(keyword1.errors);
							errors = vErrors.length;
						}
						var valid4 = _errs14 === errors;
					}
				}
			} else {
				const err10 = createError(
					instancePath + "/@context",
					"#/properties/%40context/type",
					"type",
					{ type: "array" },
					4
				);
				vErrors = pushError(vErrors, err10);
				errors++;
			}
		}
		if (data.id !== undefined) {
			if (typeof data.id !== "string") {
				const err11 = createError(
					instancePath + "/id",
					"#/properties/id/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err11);
				errors++;
			}
		}
		if (data.type !== undefined) {
			if ("AuditableItemGraphVertex" !== data.type) {
				const err12 = createError(
					instancePath + "/type",
					"#/properties/type/const",
					"const",
					{ allowedValue: "AuditableItemGraphVertex" },
					2
				);
				vErrors = pushError(vErrors, err12);
				errors++;
			}
		}
		if (data.organizationIdentity !== undefined) {
			if (typeof data.organizationIdentity !== "string") {
				const err13 = createError(
					instancePath + "/organizationIdentity",
					"#/properties/organizationIdentity/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err13);
				errors++;
			}
		}
		if (data.auditMode !== undefined) {
			if (
				!validate52(data.auditMode, {
					instancePath: instancePath + "/auditMode",
					parentData: data,
					parentDataProperty: "auditMode",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? validate52.errors : vErrors.concat(validate52.errors);
				errors = vErrors.length;
			}
		}
		if (data.annotationObject !== undefined) {
			if (
				!keyword2(data.annotationObject, {
					instancePath: instancePath + "/annotationObject",
					parentData: data,
					parentDataProperty: "annotationObject",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword2.errors : vErrors.concat(keyword2.errors);
				errors = vErrors.length;
			}
		}
		if (data.aliases !== undefined) {
			let data12 = data.aliases;
			if (Array.isArray(data12)) {
				const len2 = data12.length;
				for (let i1 = 0; i1 < len2; i1++) {
					if (
						!validate53(data12[i1], {
							instancePath: instancePath + "/aliases/" + i1,
							parentData: data12,
							parentDataProperty: i1,
							rootData,
							dynamicAnchors
						})
					) {
						vErrors = vErrors === null ? validate53.errors : vErrors.concat(validate53.errors);
						errors = vErrors.length;
					}
				}
			} else {
				const err14 = createError(
					instancePath + "/aliases",
					"#/properties/aliases/type",
					"type",
					{ type: "array" },
					4
				);
				vErrors = pushError(vErrors, err14);
				errors++;
			}
		}
		if (data.resources !== undefined) {
			let data14 = data.resources;
			if (Array.isArray(data14)) {
				const len3 = data14.length;
				for (let i2 = 0; i2 < len3; i2++) {
					if (
						!validate66(data14[i2], {
							instancePath: instancePath + "/resources/" + i2,
							parentData: data14,
							parentDataProperty: i2,
							rootData,
							dynamicAnchors
						})
					) {
						vErrors = vErrors === null ? validate66.errors : vErrors.concat(validate66.errors);
						errors = vErrors.length;
					}
				}
			} else {
				const err15 = createError(
					instancePath + "/resources",
					"#/properties/resources/type",
					"type",
					{ type: "array" },
					4
				);
				vErrors = pushError(vErrors, err15);
				errors++;
			}
		}
		if (data.edges !== undefined) {
			let data16 = data.edges;
			if (Array.isArray(data16)) {
				const len4 = data16.length;
				for (let i3 = 0; i3 < len4; i3++) {
					if (
						!validate61(data16[i3], {
							instancePath: instancePath + "/edges/" + i3,
							parentData: data16,
							parentDataProperty: i3,
							rootData,
							dynamicAnchors
						})
					) {
						vErrors = vErrors === null ? validate61.errors : vErrors.concat(validate61.errors);
						errors = vErrors.length;
					}
				}
			} else {
				const err16 = createError(
					instancePath + "/edges",
					"#/properties/edges/type",
					"type",
					{ type: "array" },
					4
				);
				vErrors = pushError(vErrors, err16);
				errors++;
			}
		}
		if (data.verified !== undefined) {
			if (typeof data.verified !== "boolean") {
				const err17 = createError(
					instancePath + "/verified",
					"#/properties/verified/type",
					"type",
					{ type: "boolean" },
					6
				);
				vErrors = pushError(vErrors, err17);
				errors++;
			}
		}
		if (data.version !== undefined) {
			let data19 = data.version;
			if (!(typeof data19 == "number" && isFinite(data19))) {
				const err18 = createError(
					instancePath + "/version",
					"#/properties/version/type",
					"type",
					{ type: "number" },
					8
				);
				vErrors = pushError(vErrors, err18);
				errors++;
			}
		}
	} else {
		const err19 = createError(instancePath, "#/type", "type", { type: "object" }, 1);
		vErrors = pushError(vErrors, err19);
		errors++;
	}
	validate74.errors = vErrors;
	return errors === 0;
}
validate74.evaluated = {
	props: {
		"@context": true,
		id: true,
		type: true,
		organizationIdentity: true,
		auditMode: true,
		annotationObject: true,
		aliases: true,
		resources: true,
		edges: true,
		verified: true,
		version: true,
		dateCreated: true,
		dateModified: true,
		dateDeleted: true
	},
	dynamicProps: false,
	dynamicItems: false
};

/**
 * Compiled validator for the AuditableItemGraphVertexList schema.
 */
export const CompiledAuditableItemGraphVertexList: ICompiledValidator = validate79;

function validate79(
	data,
	{ instancePath = "", parentData, parentDataProperty, rootData = data, dynamicAnchors = {} } = {}
) {
	/*# sourceURL="https://schema.3sixty.global/aig/AuditableItemGraphVertexList" */ let vErrors =
		null;
	let errors = 0;
	const evaluated0 = validate79.evaluated;
	if (evaluated0.dynamicProps) {
		evaluated0.props = undefined;
	}
	if (evaluated0.dynamicItems) {
		evaluated0.items = undefined;
	}
	if (data && typeof data == "object" && !Array.isArray(data)) {
		if (data["@context"] === undefined) {
			const err0 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "@context" },
				"must have required property '" + "@context" + "'"
			);
			vErrors = pushError(vErrors, err0);
			errors++;
		}
		if (data.type === undefined) {
			const err1 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "type" },
				"must have required property '" + "type" + "'"
			);
			vErrors = pushError(vErrors, err1);
			errors++;
		}
		if (data.itemListElement === undefined) {
			const err2 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "itemListElement" },
				"must have required property '" + "itemListElement" + "'"
			);
			vErrors = pushError(vErrors, err2);
			errors++;
		}
		if (data["@context"] !== undefined) {
			let data0 = data["@context"];
			if (Array.isArray(data0)) {
				if (data0.length < 2) {
					const err3 = createError(
						instancePath + "/@context",
						"#/properties/%40context/minItems",
						"minItems",
						{ limit: 2 },
						7
					);
					vErrors = pushError(vErrors, err3);
					errors++;
				}
				const len0 = data0.length;
				if (len0 > 0) {
					if ("https://schema.org" !== data0[0]) {
						const err4 = createError(
							instancePath + "/@context/0",
							"#/properties/%40context/prefixItems/0/const",
							"const",
							{ allowedValue: "https://schema.org" },
							2
						);
						vErrors = pushError(vErrors, err4);
						errors++;
					}
				}
				if (len0 > 1) {
					if ("https://schema.3sixty.global/aig/" !== data0[1]) {
						const err5 = createError(
							instancePath + "/@context/1",
							"#/properties/%40context/prefixItems/1/const",
							"const",
							{ allowedValue: "https://schema.3sixty.global/aig/" },
							2
						);
						vErrors = pushError(vErrors, err5);
						errors++;
					}
				}
				const len1 = data0.length;
				var valid2 = len1 <= 2;
				if (!valid2) {
					for (let i0 = 2; i0 < len1; i0++) {
						const _errs5 = errors;
						if (
							!keyword1(data0[i0], {
								instancePath: instancePath + "/@context/" + i0,
								parentData: data0,
								parentDataProperty: i0,
								rootData,
								dynamicAnchors
							})
						) {
							vErrors = vErrors === null ? keyword1.errors : vErrors.concat(keyword1.errors);
							errors = vErrors.length;
						}
						var valid2 = _errs5 === errors;
					}
				}
			} else {
				const err6 = createError(
					instancePath + "/@context",
					"#/properties/%40context/type",
					"type",
					{ type: "array" },
					4
				);
				vErrors = pushError(vErrors, err6);
				errors++;
			}
		}
		if (data.type !== undefined) {
			let data4 = data.type;
			if (Array.isArray(data4)) {
				if (data4.length > 2) {
					const err7 = createError(
						instancePath + "/type",
						"#/properties/type/maxItems",
						"maxItems",
						{ limit: 2 },
						9
					);
					vErrors = pushError(vErrors, err7);
					errors++;
				}
				if (data4.length < 2) {
					const err8 = createError(
						instancePath + "/type",
						"#/properties/type/minItems",
						"minItems",
						{ limit: 2 },
						7
					);
					vErrors = pushError(vErrors, err8);
					errors++;
				}
				const len2 = data4.length;
				if (len2 > 0) {
					if ("ItemList" !== data4[0]) {
						const err9 = createError(
							instancePath + "/type/0",
							"#/properties/type/prefixItems/0/const",
							"const",
							{ allowedValue: "ItemList" },
							2
						);
						vErrors = pushError(vErrors, err9);
						errors++;
					}
				}
				if (len2 > 1) {
					if ("AuditableItemGraphVertexList" !== data4[1]) {
						const err10 = createError(
							instancePath + "/type/1",
							"#/properties/type/prefixItems/1/const",
							"const",
							{ allowedValue: "AuditableItemGraphVertexList" },
							2
						);
						vErrors = pushError(vErrors, err10);
						errors++;
					}
				}
				const len3 = data4.length;
				if (!(len3 <= 2)) {
					const err11 = createError(
						instancePath + "/type",
						"#/properties/type/items",
						"items",
						{ limit: 2 },
						9
					);
					vErrors = pushError(vErrors, err11);
					errors++;
				}
			} else {
				const err12 = createError(
					instancePath + "/type",
					"#/properties/type/type",
					"type",
					{ type: "array" },
					4
				);
				vErrors = pushError(vErrors, err12);
				errors++;
			}
		}
		if (data.itemListElement !== undefined) {
			let data7 = data.itemListElement;
			if (Array.isArray(data7)) {
				const len4 = data7.length;
				for (let i1 = 0; i1 < len4; i1++) {
					if (
						!validate74(data7[i1], {
							instancePath: instancePath + "/itemListElement/" + i1,
							parentData: data7,
							parentDataProperty: i1,
							rootData,
							dynamicAnchors
						})
					) {
						vErrors = vErrors === null ? validate74.errors : vErrors.concat(validate74.errors);
						errors = vErrors.length;
					}
				}
			} else {
				const err13 = createError(
					instancePath + "/itemListElement",
					"#/properties/itemListElement/type",
					"type",
					{ type: "array" },
					4
				);
				vErrors = pushError(vErrors, err13);
				errors++;
			}
		}
	} else {
		const err14 = createError(instancePath, "#/type", "type", { type: "object" }, 1);
		vErrors = pushError(vErrors, err14);
		errors++;
	}
	validate79.errors = vErrors;
	return errors === 0;
}
validate79.evaluated = {
	props: { "@context": true, type: true, itemListElement: true },
	dynamicProps: false,
	dynamicItems: false
};

/**
 * Compiled validator for the AuditableItemGraphVertexVersionList schema.
 */
export const CompiledAuditableItemGraphVertexVersionList: ICompiledValidator = validate81;

function validate81(
	data,
	{ instancePath = "", parentData, parentDataProperty, rootData = data, dynamicAnchors = {} } = {}
) {
	/*# sourceURL="https://schema.3sixty.global/aig/AuditableItemGraphVertexVersionList" */ let vErrors =
		null;
	let errors = 0;
	const evaluated0 = validate81.evaluated;
	if (evaluated0.dynamicProps) {
		evaluated0.props = undefined;
	}
	if (evaluated0.dynamicItems) {
		evaluated0.items = undefined;
	}
	if (data && typeof data == "object" && !Array.isArray(data)) {
		if (data["@context"] === undefined) {
			const err0 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "@context" },
				"must have required property '" + "@context" + "'"
			);
			vErrors = pushError(vErrors, err0);
			errors++;
		}
		if (data.type === undefined) {
			const err1 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "type" },
				"must have required property '" + "type" + "'"
			);
			vErrors = pushError(vErrors, err1);
			errors++;
		}
		if (data.itemListElement === undefined) {
			const err2 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "itemListElement" },
				"must have required property '" + "itemListElement" + "'"
			);
			vErrors = pushError(vErrors, err2);
			errors++;
		}
		if (data["@context"] !== undefined) {
			let data0 = data["@context"];
			if (Array.isArray(data0)) {
				if (data0.length < 2) {
					const err3 = createError(
						instancePath + "/@context",
						"#/properties/%40context/minItems",
						"minItems",
						{ limit: 2 },
						7
					);
					vErrors = pushError(vErrors, err3);
					errors++;
				}
				const len0 = data0.length;
				if (len0 > 0) {
					if ("https://schema.org" !== data0[0]) {
						const err4 = createError(
							instancePath + "/@context/0",
							"#/properties/%40context/prefixItems/0/const",
							"const",
							{ allowedValue: "https://schema.org" },
							2
						);
						vErrors = pushError(vErrors, err4);
						errors++;
					}
				}
				if (len0 > 1) {
					if ("https://schema.3sixty.global/aig/" !== data0[1]) {
						const err5 = createError(
							instancePath + "/@context/1",
							"#/properties/%40context/prefixItems/1/const",
							"const",
							{ allowedValue: "https://schema.3sixty.global/aig/" },
							2
						);
						vErrors = pushError(vErrors, err5);
						errors++;
					}
				}
				const len1 = data0.length;
				var valid2 = len1 <= 2;
				if (!valid2) {
					for (let i0 = 2; i0 < len1; i0++) {
						const _errs5 = errors;
						if (
							!keyword1(data0[i0], {
								instancePath: instancePath + "/@context/" + i0,
								parentData: data0,
								parentDataProperty: i0,
								rootData,
								dynamicAnchors
							})
						) {
							vErrors = vErrors === null ? keyword1.errors : vErrors.concat(keyword1.errors);
							errors = vErrors.length;
						}
						var valid2 = _errs5 === errors;
					}
				}
			} else {
				const err6 = createError(
					instancePath + "/@context",
					"#/properties/%40context/type",
					"type",
					{ type: "array" },
					4
				);
				vErrors = pushError(vErrors, err6);
				errors++;
			}
		}
		if (data.type !== undefined) {
			let data4 = data.type;
			if (Array.isArray(data4)) {
				if (data4.length > 2) {
					const err7 = createError(
						instancePath + "/type",
						"#/properties/type/maxItems",
						"maxItems",
						{ limit: 2 },
						9
					);
					vErrors = pushError(vErrors, err7);
					errors++;
				}
				if (data4.length < 2) {
					const err8 = createError(
						instancePath + "/type",
						"#/properties/type/minItems",
						"minItems",
						{ limit: 2 },
						7
					);
					vErrors = pushError(vErrors, err8);
					errors++;
				}
				const len2 = data4.length;
				if (len2 > 0) {
					if ("ItemList" !== data4[0]) {
						const err9 = createError(
							instancePath + "/type/0",
							"#/properties/type/prefixItems/0/const",
							"const",
							{ allowedValue: "ItemList" },
							2
						);
						vErrors = pushError(vErrors, err9);
						errors++;
					}
				}
				if (len2 > 1) {
					if ("AuditableItemGraphVertexVersionList" !== data4[1]) {
						const err10 = createError(
							instancePath + "/type/1",
							"#/properties/type/prefixItems/1/const",
							"const",
							{ allowedValue: "AuditableItemGraphVertexVersionList" },
							2
						);
						vErrors = pushError(vErrors, err10);
						errors++;
					}
				}
				const len3 = data4.length;
				if (!(len3 <= 2)) {
					const err11 = createError(
						instancePath + "/type",
						"#/properties/type/items",
						"items",
						{ limit: 2 },
						9
					);
					vErrors = pushError(vErrors, err11);
					errors++;
				}
			} else {
				const err12 = createError(
					instancePath + "/type",
					"#/properties/type/type",
					"type",
					{ type: "array" },
					4
				);
				vErrors = pushError(vErrors, err12);
				errors++;
			}
		}
		if (data.itemListElement !== undefined) {
			let data7 = data.itemListElement;
			if (Array.isArray(data7)) {
				const len4 = data7.length;
				for (let i1 = 0; i1 < len4; i1++) {
					let data8 = data7[i1];
					if (data8 && typeof data8 == "object" && !Array.isArray(data8)) {
						if (data8.version === undefined) {
							const err13 = createError(
								instancePath + "/itemListElement/" + i1,
								"#/properties/itemListElement/items/required",
								"required",
								{ missingProperty: "version" },
								"must have required property '" + "version" + "'"
							);
							vErrors = pushError(vErrors, err13);
							errors++;
						}
						if (data8.dateCreated === undefined) {
							const err14 = createError(
								instancePath + "/itemListElement/" + i1,
								"#/properties/itemListElement/items/required",
								"required",
								{ missingProperty: "dateCreated" },
								"must have required property '" + "dateCreated" + "'"
							);
							vErrors = pushError(vErrors, err14);
							errors++;
						}
						if (data8.version !== undefined) {
							let data9 = data8.version;
							if (!(typeof data9 == "number" && isFinite(data9))) {
								const err15 = createError(
									instancePath + "/itemListElement/" + i1 + "/version",
									"#/properties/itemListElement/items/properties/version/type",
									"type",
									{ type: "number" },
									8
								);
								vErrors = pushError(vErrors, err15);
								errors++;
							}
						}
						if (data8.dateCreated !== undefined) {
							if (typeof data8.dateCreated !== "string") {
								const err16 = createError(
									instancePath + "/itemListElement/" + i1 + "/dateCreated",
									"#/properties/itemListElement/items/properties/dateCreated/type",
									"type",
									{ type: "string" },
									0
								);
								vErrors = pushError(vErrors, err16);
								errors++;
							}
						}
					} else {
						const err17 = createError(
							instancePath + "/itemListElement/" + i1,
							"#/properties/itemListElement/items/type",
							"type",
							{ type: "object" },
							1
						);
						vErrors = pushError(vErrors, err17);
						errors++;
					}
				}
			} else {
				const err18 = createError(
					instancePath + "/itemListElement",
					"#/properties/itemListElement/type",
					"type",
					{ type: "array" },
					4
				);
				vErrors = pushError(vErrors, err18);
				errors++;
			}
		}
	} else {
		const err19 = createError(instancePath, "#/type", "type", { type: "object" }, 1);
		vErrors = pushError(vErrors, err19);
		errors++;
	}
	validate81.errors = vErrors;
	return errors === 0;
}
validate81.evaluated = {
	props: { "@context": true, type: true, itemListElement: true },
	dynamicProps: false,
	dynamicItems: false
};
